# Configuration parameters for data recording node.

# Please keep your changes to this path local
output_directory: '/home/your/path/here'

topics:
  - '/camera/aligned_depth_to_color/image_raw'
  - '/camera/aligned_depth_to_color/camera_info'
  - '/camera/color/image_raw'
  - '/camera/color/camera_info'
  - '/ggcnn_cout/command'
  - '/tf'
  - '/data_recording/annotations'
